config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'competences' => 'home#skills', as: :skills
  get 'a-propos' => 'home#about_us', as: :about_us
  get 'nos-projets' => 'home#portfolio', as: :portfolio

  get 'administrator/subject' => 'subjects#new', as: :subject
  post 'administrator/subject/create' => 'subjects#create', as: :create_subject
  get 'administrator/subject/create' => 'subjects#new'
  get 'administrator/subjects' => 'subjects#show', as: :subjects
  get 'administrator/subject/edit/:subject_id' => 'subjects#edit', as: :edit_subject
  post 'administrator/subject/update/:subject_id' => 'subjects#update', as: :update_subject
  get 'administrator/subject/update/:subject_id' => 'subjects#edit'
  get 'administrator/subject/enable/:subject_id' => 'subjects#enable', as: :enable_subject
  get 'administrator/subject/disable/:subject_id' => 'subjects#disable', as: :disable_subject

  get 'administrator/budget' => 'budgets#new', as: :budget
  post 'administrator/budget/create' => 'budgets#create', as: :create_budget
  get 'administrator/budget/create' => 'budgets#new'
  get 'administrator/budgets' => 'budgets#show', as: :budgets
  get 'administrator/budget/edit/:budget_id' => 'budgets#edit', as: :edit_budget
  post 'administrator/budget/update/:budget_id' => 'budgets#update', as: :update_budget
  get 'administrator/budget/update/:budget_id' => 'budgets#edit'
  get 'administrator/budget/enable/:budget_id' => 'budgets#enable', as: :enable_budget
  get 'administrator/budget/disable/:budget_id' => 'budgets#disable', as: :disable_budget

  get 'administrator/project' => 'projects#new', as: :project
  post 'administrator/project/create' => 'projects#create', as: :create_project
  get 'administrator/project/create' => 'projects#new'
  get 'administrator/projects' => 'projects#show', as: :projects

  get 'administrator/completed_project' => 'completed_projects#new', as: :completed_project
  post 'administrator/completed_project/create' => 'completed_projects#create', as: :create_completed_project
  get 'administrator/completed_project/create' => 'completed_projects#new'
  get 'administrator/completed_projects' => 'completed_projects#show', as: :completed_projects
  get "portfolio/:completed_project_id/details" => "completed_projects#details", as: :completed_project_details

  get 'administrator/completed_project_category' => 'completed_project_categories#new', as: :completed_project_category
  post 'administrator/completed_project_category/create' => 'completed_project_categories#create', as: :create_completed_project_category
  get 'administrator/completed_project_category/create' => 'completed_project_categories#new'
  get 'administrator/completed_project_categories' => 'completed_project_categories#show', as: :completed_project_categories
  get 'administrator/completed_project_category/edit/:completed_project_category_id' => 'completed_project_categories#edit', as: :edit_completed_project_category
  post 'administrator/completed_project_category/update/:completed_project_category_id' => 'completed_project_categories#update', as: :update_completed_project_category
  get 'administrator/completed_project_category/update/:completed_project_category_id' => 'completed_project_categories#edit'
  get 'administrator/completed_project_category/enable/:completed_project_category_id' => 'completed_project_categories#enable', as: :enable_completed_project_category
  get 'administrator/completed_project_category/disable/:completed_project_category_id' => 'completed_project_categories#disable', as: :disable_completed_project_category

  get 'contact' => 'contacts#new', as: :contact
  post 'contact/create' => 'contacts#create', as: :create_contact
  get 'contact/create' => 'contacts#new'
  get 'administrator/contacts' => 'contacts#show', as: :contacts

  get '*rogue_url', :to => 'errors#routing'
  post '*rogue_url', :to => 'errors#routing'
end

app/models/budget.rb
class Budget < ActiveRecord::Base
  # Handle project planner budget

  #Relationships
  has_many :project

  # Accessible fields
  attr_accessible :label, :published, :created_at

  # Renaming attributes into more friendly text
  HUMANIZED_ATTRIBUTES = {
    label: 'Libellé',
    published: 'Statut'
  }

  # Using friendly attribute name if it exists and default name otherwise
  def self.human_attribute_name(attr, option = {})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end

  #Validations
  validates :label, presence: true
  validates :label, length: {in: 5..100}
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  layout 'administrator'

  def new
    @page_title = "START::Budget"
    @budget = Budget.new
  end

  def create
    @page_title = "START::Budget"
    @budget = Budget.new(params[:budget])

    if @budget.save
      @budget = Budget.new
      flash.now[:success] = "Le budget a été créé"
    else
      flash.now[:error] = @budget.errors.full_messages.map{ |msg| "#{msg}<br />" }.join
    end

    render :new
  end

  def show
    @page_title = "START::Budgets"
    @budgets = Budget.all.order('created_at ASC')
  end

  def edit
    @page_title = "START::Budget"
    @budget = Budget.find_by_id(params[:budget_id])

    unless @budget
      render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
    end
  end

  def update
    @budget = Budget.find_by_id(params[:budget_id])

    if @budget.blank?
      render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
    else
      @budget.update_attributes(params[:budget])
      if @budget.errors.full_messages.blank?
        flash.now[:success] = "Le budget a été mis à jour."
      else
        flash.now[:error] = @budget.errors.full_messages.map { |msg| "<p>#{msg}</p>" }.join
        @budget = Budget.find_by_id(params[:budget_id])
      end

      render :edit, id: @budget.id
    end
  end

  def enable
    enable_disable(true, 'activé')
  end

  def disable
    enable_disable(false, 'désactivé')
  end

  def enable_disable(status, message)
    budget = Budget.find_by_id(params[:budget_id])
    if budget.blank?
      render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
    else
      budget.update_attribute(:published, status)
      flash[:success] = "Le budget: #{budget.label} a été #{message}."

      redirect_to budgets_path
    end
  end

end

app/helpers/budgets_helper.rb
module BudgetsHelper
  def budget_messages!
    [:error, :alert, :success, :notice].each do |key|
      if flash[key]
        @key = key
        @notification_message = flash[key]
      end
    end

    return "" if @notification_message.blank?

    messages!
  end
end

app/views/budgets/edit.html.erb
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<%= budget_path %>">Nouveau budget</a></li>
    <li><a href="<%= budgets_path %>">Liste des budgets</a></li>
</ul>
<!-- END BREADCRUMB -->


<div class="page-content-wrap">

  <!-- BEGIN ROW -->
  <div class="row">
      <div class="col-md-12">


          <%= form_for @budget, url: update_budget_path, method: :post,  html: {class: "form-horizontal"} do |f| %>
          <div class="panel panel-default">
              <div class="panel-heading">
                  <h3 class="panel-title">Modifier le budget: <strong><%= @budget.label %></strong></h3>
              </div>
              <div class="panel-body">
                  <p>Ce formulaire est destiné à la modification des budgets sur lesquels les internautes peuvent écrire qui seront affichés dans le formulaire de contacts.</p>
              </div>
              <div class="panel-body">

                <%= budget_messages! %>

                <div class="form-group">

                  <%= f.label :label, class: 'col-md-3 col-xs-12 control-label' %>
                  <div class="col-md-6 col-xs-12">
                    <div class="input-group">
                      <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                      <%= f.text_field :label, class: 'form-control', placeholder: "Veuillez entrer l'intitulé du budget" %>
                    </div>
                  </div>
                </div>

              </div>
              <div class="panel-footer">
                <button class="btn btn-primary">Valider</button>
              </div>
          </div>
          <% end %>

      </div>
  </div>
  <!-- END ROW -->

</div>

app/views/budgets/new.html.erb
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<%= budget_path %>">Nouveau budget</a></li>
    <li><a href="<%= budgets_path %>">Liste des budgets</a></li>
</ul>
<!-- END BREADCRUMB -->


<div class="page-content-wrap">

  <!-- BEGIN ROW -->
  <div class="row">
      <div class="col-md-12">


          <%= form_for @budget, url: create_budget_path, method: :post,  html: {class: "form-horizontal"} do |f| %>
          <div class="panel panel-default">
              <div class="panel-heading">
                  <h3 class="panel-title">Créer un <strong>Budget</strong></h3>
              </div>
              <div class="panel-body">
                  <p>Ce formulaire est destiné à la création des budgets qui seront affichés dans le formulaire de demande d'étude de projet.</p>
              </div>
              <div class="panel-body">

                <%= budget_messages! %>

                <div class="form-group">
                  <%= f.label :label, class: 'col-md-3 col-xs-12 control-label' %>
                  <div class="col-md-6 col-xs-12">
                    <div class="input-group">
                      <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                      <%= f.text_field :label, class: 'form-control', placeholder: "Veuillez entrer l'intitulé du budget" %>
                    </div>
                  </div>
                </div>

              </div>
              <div class="panel-footer">
                <button class="btn btn-primary">Valider</button>
              </div>
          </div>
          <% end %>

      </div>
  </div>
  <!-- END ROW -->

</div>

app/views/budgets/show.html.erb
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
  <li><a href="<%= budget_path %>">Nouveau budget</a></li>
  <li><a href="<%= budgets_path %>">Liste des budgets</a></li>
</ul>
<!-- END BREADCRUMB -->


<div class="page-content-wrap">

  <!-- BEGIN ROW -->
  <div class="row">
    <div class="col-md-12">

      <!-- START DEFAULT DATATABLE -->
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Liste des budgets</h3>
          <ul class="panel-controls">
            <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
          </ul>
        </div>
        <div class="panel-body">
          <%= notification_messages! %>
          <table class="table datatable">
            <thead>
              <tr>
                <th><%= Budget.human_attribute_name("label") %></th>
                <th><%= Budget.human_attribute_name("published") %></th>
                <th>Date de création</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @budgets.each do |budget| %>
                <tr>
                  <td>
                    <%= budget.label %>
                  </td>
                  <td>
                    <% if budget.published == false %>
                      <div class="list-group-status status-offline"></div>
                    <% else %>
                      <div class="list-group-status status-online"></div>
                    <% end %>
                  </td>
                  <td>
                    <%= budget.created_at.strftime("%d-%m-%Y") + " à " + budget.created_at.strftime("%Hh %Mmn") %>
                  </td>
                  <td>
                    <a href = "<%= edit_budget_path(budget.id) %>" style = "text-decoration: none;">
                      <span class="fa fa-pencil" style = "margin-right: 15px;" data-toggle="tooltip" data-placement="top" title="" data-original-title="Editer le budget"></span>
                    </a>
                    <% if budget.published == false %>
                      <a href = "<%= enable_budget_path(budget.id) %>">
                        <span class="fa fa-check" data-toggle="tooltip" data-placement="top" title="" data-original-title="Activer le budget"></span>
                      </a>
                    <% else %>
                      <a href = "<%= disable_budget_path(budget.id) %>"  style = "text-decoration: none;">
                        <span class="fa fa-times-circle" data-toggle="tooltip" data-placement="top" title="" data-original-title="Désactiver le budget"></span>
                      </a>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <!-- END DEFAULT DATATABLE -->
    </div>
  </div>
</div>