config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'competences' => 'home#skills', as: :skills
  get 'a-propos' => 'home#about_us', as: :about_us
  get 'nos-projets' => 'home#portfolio', as: :portfolio

  get 'administrator/subject' => 'subjects#new', as: :subject
  post 'administrator/subject/create' => 'subjects#create', as: :create_subject
  get 'administrator/subject/create' => 'subjects#new'
  get 'administrator/subjects' => 'subjects#show', as: :subjects
  get 'administrator/subject/edit/:subject_id' => 'subjects#edit', as: :edit_subject
  post 'administrator/subject/update/:subject_id' => 'subjects#update', as: :update_subject
  get 'administrator/subject/update/:subject_id' => 'subjects#edit'
  get 'administrator/subject/enable/:subject_id' => 'subjects#enable', as: :enable_subject
  get 'administrator/subject/disable/:subject_id' => 'subjects#disable', as: :disable_subject

  get 'administrator/budget' => 'budgets#new', as: :budget
  post 'administrator/budget/create' => 'budgets#create', as: :create_budget
  get 'administrator/budget/create' => 'budgets#new'
  get 'administrator/budgets' => 'budgets#show', as: :budgets
  get 'administrator/budget/edit/:budget_id' => 'budgets#edit', as: :edit_budget
  post 'administrator/budget/update/:budget_id' => 'budgets#update', as: :update_budget
  get 'administrator/budget/update/:budget_id' => 'budgets#edit'
  get 'administrator/budget/enable/:budget_id' => 'budgets#enable', as: :enable_budget
  get 'administrator/budget/disable/:budget_id' => 'budgets#disable', as: :disable_budget

  get 'administrator/project' => 'projects#new', as: :project
  post 'administrator/project/create' => 'projects#create', as: :create_project
  get 'administrator/project/create' => 'projects#new'
  get 'administrator/projects' => 'projects#show', as: :projects

  get 'administrator/completed_project' => 'completed_projects#new', as: :completed_project
  post 'administrator/completed_project/create' => 'completed_projects#create', as: :create_completed_project
  get 'administrator/completed_project/create' => 'completed_projects#new'
  get 'administrator/completed_projects' => 'completed_projects#show', as: :completed_projects
  get "portfolio/:completed_project_id/details" => "completed_projects#details", as: :completed_project_details

  get 'administrator/completed_project_category' => 'completed_project_categories#new', as: :completed_project_category
  post 'administrator/completed_project_category/create' => 'completed_project_categories#create', as: :create_completed_project_category
  get 'administrator/completed_project_category/create' => 'completed_project_categories#new'
  get 'administrator/completed_project_categories' => 'completed_project_categories#show', as: :completed_project_categories
  get 'administrator/completed_project_category/edit/:completed_project_category_id' => 'completed_project_categories#edit', as: :edit_completed_project_category
  post 'administrator/completed_project_category/update/:completed_project_category_id' => 'completed_project_categories#update', as: :update_completed_project_category
  get 'administrator/completed_project_category/update/:completed_project_category_id' => 'completed_project_categories#edit'
  get 'administrator/completed_project_category/enable/:completed_project_category_id' => 'completed_project_categories#enable', as: :enable_completed_project_category
  get 'administrator/completed_project_category/disable/:completed_project_category_id' => 'completed_project_categories#disable', as: :disable_completed_project_category

  get 'contact' => 'contacts#new', as: :contact
  post 'contact/create' => 'contacts#create', as: :create_contact
  get 'contact/create' => 'contacts#new'
  get 'administrator/contacts' => 'contacts#show', as: :contacts

  get '*rogue_url', :to => 'errors#routing'
  post '*rogue_url', :to => 'errors#routing'
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  # Handle contact email subjects

  #Relationships
  has_many :contacts

  # Accessible fields
  attr_accessible :name, :published

  # Renaming attributes into more friendly text
  HUMANIZED_ATTRIBUTES = {
    name: 'Intitulé',
    published: 'Statut'
  }

  # Using friendly attribute name if it exists and default name otherwise
  def self.human_attribute_name(attr, option = {})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end

  #Validations
  validates :name, presence: true
  validates :name, length: {in: 4..100}
  validates :name, uniqueness: true
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  layout 'administrator'

  def new
    @page_title = "START::Sujet"
    @subject = Subject.new
  end

  def create
    @page_title = "START::Sujet"
    @subject = Subject.new(params[:subject])

    if @subject.save
      @subject = Subject.new
      flash.now[:success] = "Le sujet a été créé"
    else
      flash.now[:error] = @subject.errors.full_messages.map{ |msg| "#{msg}<br />" }.join
    end

    render :new
  end

  def show
    @page_title = "START::Sujets"
    @subjects = Subject.all.order('name ASC')
  end

  def edit
    @page_title = "START::Sujet"
    @subject = Subject.find_by_id(params[:subject_id])

    unless @subject
      render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
    end
  end

  def update
    @subject = Subject.find_by_id(params[:subject_id])

    if @subject.blank?
      render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
    else
      @subject.update_attributes(params[:subject])
      if @subject.errors.full_messages.blank?
        flash.now[:success] = "Le sujet a été mis à jour."
      else
        flash.now[:error] = @subject.errors.full_messages.map { |msg| "<p>#{msg}</p>" }.join
        @subject = Subject.find_by_id(params[:subject_id])
      end

      render :edit, id: @subject.id
    end
  end

  def enable
    enable_disable(true, 'activé')
  end

  def disable
    enable_disable(false, 'désactivé')
  end

  def enable_disable(status, message)
    subject = Subject.find_by_id(params[:subject_id])
    if subject.blank?
      render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
    else
      subject.update_attribute(:published, status)
      flash[:success] = "Le sujet: #{subject.name} a été #{message}."

      redirect_to subjects_path
    end
  end

end

app/helpers/subjects_helper.rb
module SubjectsHelper

  def subject_messages!
    [:error, :alert, :success, :notice].each do |key|
      if flash[key]
        @key = key
        @notification_message = flash[key]
      end
    end

    return "" if @notification_message.blank?

    messages!
  end

end

app/views/subjects/edit.html.erb
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<%= subject_path %>">Nouveau sujet</a></li>
    <li><a href="<%= subjects_path %>">Liste des sujets</a></li>
</ul>
<!-- END BREADCRUMB -->


<div class="page-content-wrap">

  <!-- BEGIN ROW -->
  <div class="row">
      <div class="col-md-12">


          <%= form_for @subject, url: update_subject_path, method: :post,  html: {class: "form-horizontal"} do |f| %>
          <div class="panel panel-default">
              <div class="panel-heading">
                  <h3 class="panel-title">Modifier le sujet: <strong><%= @subject.name %></strong></h3>
              </div>
              <div class="panel-body">
                  <p>Ce formulaire est destiné à la modification des sujets sur lesquels les internautes peuvent écrire qui seront affichés dans le formulaire de contacts.</p>
              </div>
              <div class="panel-body">

                <%= subject_messages! %>

                <div class="form-group">

                  <%= f.label :name, class: 'col-md-3 col-xs-12 control-label' %>
                  <div class="col-md-6 col-xs-12">
                    <div class="input-group">
                      <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                      <%= f.text_field :name, class: 'form-control', placeholder: "Veuillez entrer l'intitulé du sujet" %>
                    </div>
                  </div>
                </div>

              </div>
              <div class="panel-footer">
                <button class="btn btn-primary">Valider</button>
              </div>
          </div>
          <% end %>

      </div>
  </div>
  <!-- END ROW -->

</div>

app/views/subjects/new.html.erb
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<%= subject_path %>">Nouveau sujet</a></li>
    <li><a href="<%= subjects_path %>">Liste des sujets</a></li>
</ul>
<!-- END BREADCRUMB -->


<div class="page-content-wrap">

  <!-- BEGIN ROW -->
  <div class="row">
      <div class="col-md-12">


          <%= form_for @subject, url: create_subject_path, method: :post,  html: {class: "form-horizontal"} do |f| %>
          <div class="panel panel-default">
              <div class="panel-heading">
                  <h3 class="panel-title">Créer un <strong>Sujet</strong></h3>
              </div>
              <div class="panel-body">
                  <p>Ce formulaire est destiné à la création des sujets sur lesquels les internautes peuvent écrire qui seront affichés dans le formulaire de contacts.</p>
              </div>
              <div class="panel-body">

                <%= subject_messages! %>

                <div class="form-group">
                  <%= f.label :name, class: 'col-md-3 col-xs-12 control-label' %>
                  <div class="col-md-6 col-xs-12">
                    <div class="input-group">
                      <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                      <%= f.text_field :name, class: 'form-control', placeholder: "Veuillez entrer l'intitulé du sujet" %>
                    </div>
                  </div>
                </div>

              </div>
              <div class="panel-footer">
                <button class="btn btn-primary">Valider</button>
              </div>
          </div>
          <% end %>

      </div>
  </div>
  <!-- END ROW -->

</div>

app/views/subjects/show.html.erb
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
  <li><a href="<%= subject_path %>">Nouveau sujet</a></li>
  <li><a href="<%= subjects_path %>">Liste des sujets</a></li>
</ul>
<!-- END BREADCRUMB -->


<div class="page-content-wrap">

  <!-- BEGIN ROW -->
  <div class="row">
    <div class="col-md-12">

      <!-- START DEFAULT DATATABLE -->
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Liste des sujets</h3>
          <ul class="panel-controls">
            <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
          </ul>
        </div>
        <div class="panel-body">
          <%= notification_messages! %>
          <table class="table datatable">
            <thead>
              <tr>
                <th><%= Subject.human_attribute_name("name") %></th>
                <th><%= Subject.human_attribute_name("published") %></th>
                <th>Date de création</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @subjects.each do |subject| %>
                <tr>
                  <td>
                    <%= subject.name %>
                  </td>
                  <td>
                    <% if subject.published == false %>
                      <div class="list-group-status status-offline"></div>
                    <% else %>
                      <div class="list-group-status status-online"></div>
                    <% end %>
                  </td>
                  <td>
                    <%= subject.created_at.strftime("%d-%m-%Y") + " à " + subject.created_at.strftime("%Hh %Mmn") %>
                  </td>
                  <td>
                    <a href = "<%= edit_subject_path(subject.id) %>" style = "text-decoration: none;">
                      <span class="fa fa-pencil" style = "margin-right: 15px;" data-toggle="tooltip" data-placement="top" title="" data-original-title="Editer le sujet"></span>
                    </a>
                    <% if subject.published == false %>
                      <a href = "<%= enable_subject_path(subject.id) %>">
                        <span class="fa fa-check" data-toggle="tooltip" data-placement="top" title="" data-original-title="Activer le sujet"></span>
                      </a>
                    <% else %>
                      <a href = "<%= disable_subject_path(subject.id) %>"  style = "text-decoration: none;">
                        <span class="fa fa-times-circle" data-toggle="tooltip" data-placement="top" title="" data-original-title="Désactiver le sujet"></span>
                      </a>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <!-- END DEFAULT DATATABLE -->
    </div>
  </div>
</div>