config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'competences' => 'home#skills', as: :skills
  get 'a-propos' => 'home#about_us', as: :about_us
  get 'nos-projets' => 'home#portfolio', as: :portfolio

  get 'administrator/subject' => 'subjects#new', as: :subject
  post 'administrator/subject/create' => 'subjects#create', as: :create_subject
  get 'administrator/subject/create' => 'subjects#new'
  get 'administrator/subjects' => 'subjects#show', as: :subjects
  get 'administrator/subject/edit/:subject_id' => 'subjects#edit', as: :edit_subject
  post 'administrator/subject/update/:subject_id' => 'subjects#update', as: :update_subject
  get 'administrator/subject/update/:subject_id' => 'subjects#edit'
  get 'administrator/subject/enable/:subject_id' => 'subjects#enable', as: :enable_subject
  get 'administrator/subject/disable/:subject_id' => 'subjects#disable', as: :disable_subject

  get 'administrator/budget' => 'budgets#new', as: :budget
  post 'administrator/budget/create' => 'budgets#create', as: :create_budget
  get 'administrator/budget/create' => 'budgets#new'
  get 'administrator/budgets' => 'budgets#show', as: :budgets
  get 'administrator/budget/edit/:budget_id' => 'budgets#edit', as: :edit_budget
  post 'administrator/budget/update/:budget_id' => 'budgets#update', as: :update_budget
  get 'administrator/budget/update/:budget_id' => 'budgets#edit'
  get 'administrator/budget/enable/:budget_id' => 'budgets#enable', as: :enable_budget
  get 'administrator/budget/disable/:budget_id' => 'budgets#disable', as: :disable_budget

  get 'administrator/project' => 'projects#new', as: :project
  post 'administrator/project/create' => 'projects#create', as: :create_project
  get 'administrator/project/create' => 'projects#new'
  get 'administrator/projects' => 'projects#show', as: :projects

  get 'administrator/completed_project' => 'completed_projects#new', as: :completed_project
  post 'administrator/completed_project/create' => 'completed_projects#create', as: :create_completed_project
  get 'administrator/completed_project/create' => 'completed_projects#new'
  get 'administrator/completed_projects' => 'completed_projects#show', as: :completed_projects
  get "portfolio/:completed_project_id/details" => "completed_projects#details", as: :completed_project_details

  get 'administrator/completed_project_category' => 'completed_project_categories#new', as: :completed_project_category
  post 'administrator/completed_project_category/create' => 'completed_project_categories#create', as: :create_completed_project_category
  get 'administrator/completed_project_category/create' => 'completed_project_categories#new'
  get 'administrator/completed_project_categories' => 'completed_project_categories#show', as: :completed_project_categories
  get 'administrator/completed_project_category/edit/:completed_project_category_id' => 'completed_project_categories#edit', as: :edit_completed_project_category
  post 'administrator/completed_project_category/update/:completed_project_category_id' => 'completed_project_categories#update', as: :update_completed_project_category
  get 'administrator/completed_project_category/update/:completed_project_category_id' => 'completed_project_categories#edit'
  get 'administrator/completed_project_category/enable/:completed_project_category_id' => 'completed_project_categories#enable', as: :enable_completed_project_category
  get 'administrator/completed_project_category/disable/:completed_project_category_id' => 'completed_project_categories#disable', as: :disable_completed_project_category

  get 'contact' => 'contacts#new', as: :contact
  post 'contact/create' => 'contacts#create', as: :create_contact
  get 'contact/create' => 'contacts#new'
  get 'administrator/contacts' => 'contacts#show', as: :contacts

  get '*rogue_url', :to => 'errors#routing'
  post '*rogue_url', :to => 'errors#routing'
end

app/models/completed_project_category.rb
class CompletedProjectCategory < ActiveRecord::Base
  # Handle contact email subjects

  #Relationships
  has_many :completed_projects

  # Accessible fields
  attr_accessible :name, :published, :created_at, :id

  # Renaming attributes into more friendly text
  HUMANIZED_ATTRIBUTES = {
    name: 'Nom',
    published: 'Statut'
  }

  # Using friendly attribute name if it exists and default name otherwise
  def self.human_attribute_name(attr, option = {})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end

  #Validations
  validates :name, presence: true
  validates :name, length: {in: 4..100}
  validates :name, uniqueness: true
end

app/controllers/completed_project_categories_controller.rb
class CompletedProjectCategoriesController < ApplicationController
  layout 'administrator'

  def new
    @page_title = "START::Catégories de projets terminés"
    @completed_project_category = CompletedProjectCategory.new
  end

  def create
    @page_title = "START::Catégories de projets terminés"
    @completed_project_category = CompletedProjectCategory.new(params[:completed_project_category])

    if @completed_project_category.save
      @completed_project_category = CompletedProjectCategory.new
      flash.now[:success] = "La catégorie a été créée"
    else
      flash.now[:error] = @completed_project_category.errors.full_messages.map{ |msg| "#{msg}<br />" }.join
    end

    render :new
  end

  def show
    @page_title = "START::Catégories de projets terminés"
    @completed_project_categories = CompletedProjectCategory.all.order('name ASC')
  end

  def edit
    @page_title = "START::Catégories de projets terminés"
    @completed_project_category = CompletedProjectCategory.find_by_id(params[:completed_project_category_id])

    unless @completed_project_category
      render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
    end
  end

  def update
    @completed_project_category = CompletedProjectCategory.find_by_id(params[:completed_project_category_id])

    if @completed_project_category.blank?
      render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
    else
      @completed_project_category.update_attributes(params[:completed_project_category])
      if @completed_project_category.errors.full_messages.blank?
        flash.now[:success] = "La catégorie a été mise à jour."
      else
        flash.now[:error] = @completed_project_category.errors.full_messages.map { |msg| "<p>#{msg}</p>" }.join
        @completed_project_category = CompletedProjectCategory.find_by_id(params[:completed_project_category_id])
      end

      render :edit, id: @completed_project_category.id
    end
  end

  def enable
    enable_disable(true, 'activée')
  end

  def disable
    enable_disable(false, 'désactivée')
  end

  def enable_disable(status, message)
    completed_project_category = CompletedProjectCategory.find_by_id(params[:completed_project_category_id])
    if completed_project_category.blank?
      render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
    else
      completed_project_category.update_attribute(:published, status)
      flash[:success] = "La catégorie: #{completed_project_category.name} a été #{message}."

      redirect_to completed_project_categories_path
    end
  end

end

app/helpers/completed_project_categories_helper.rb
module CompletedProjectCategoriesHelper
  def completed_project_category_messages!
    [:error, :alert, :success, :notice].each do |key|
      if flash[key]
        @key = key
        @notification_message = flash[key]
      end
    end

    return "" if @notification_message.blank?

    messages!
  end
end

app/views/completed_project_categories/edit.html.erb
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<%= completed_project_category_path %>">Nouvelle catégorie de projets</a></li>
    <li><a href="<%= completed_project_categories_path %>">Liste des catégories de projets</a></li>
</ul>
<!-- END BREADCRUMB -->


<div class="page-content-wrap">

  <!-- BEGIN ROW -->
  <div class="row">
      <div class="col-md-12">


          <%= form_for @completed_project_category, url: update_completed_project_category_path, method: :post,  html: {class: "form-horizontal"} do |f| %>
          <div class="panel panel-default">
              <div class="panel-heading">
                  <h3 class="panel-title">Modifier la catégorie <strong><%= @completed_project_category.name %></strong></h3>
              </div>
              <div class="panel-body">
                  <p>Ce formulaire est destiné à la modification des catégorie de projets.</p>
              </div>
              <div class="panel-body">

                <%= completed_project_category_messages! %>

                <div class="form-group">
                  <%= f.label :name, class: 'col-md-3 col-xs-12 control-label' %>
                  <div class="col-md-6 col-xs-12">
                    <div class="input-group">
                      <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                      <%= f.text_field :name, class: 'form-control', placeholder: "Veuillez entrer le titre de la catégorie" %>
                    </div>
                  </div>
                </div>

              </div>
              <div class="panel-footer">
                <button class="btn btn-primary">Valider</button>
              </div>
          </div>
          <% end %>

      </div>
  </div>
  <!-- END ROW -->

</div>

app/views/completed_project_categories/new.html.erb
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<%= completed_project_category_path %>">Nouvelle catégorie de projets</a></li>
    <li><a href="<%= completed_project_categories_path %>">Liste des catégories de projets</a></li>
</ul>
<!-- END BREADCRUMB -->


<div class="page-content-wrap">

  <!-- BEGIN ROW -->
  <div class="row">
      <div class="col-md-12">


          <%= form_for @completed_project_category, url: create_completed_project_category_path, method: :post,  html: {class: "form-horizontal"} do |f| %>
          <div class="panel panel-default">
              <div class="panel-heading">
                  <h3 class="panel-title">Créer une <strong>catégorie de projets</strong></h3>
              </div>
              <div class="panel-body">
                  <p>Ce formulaire est destiné à la création des catégorie de projets.</p>
              </div>
              <div class="panel-body">

                <%= completed_project_category_messages! %>

                <div class="form-group">
                  <%= f.label :name, class: 'col-md-3 col-xs-12 control-label' %>
                  <div class="col-md-6 col-xs-12">
                    <div class="input-group">
                      <span class="input-group-addon"><span class="fa fa-pencil"></span></span>
                      <%= f.text_field :name, class: 'form-control', placeholder: "Veuillez entrer le titre de la catégorie" %>
                    </div>
                  </div>
                </div>

              </div>
              <div class="panel-footer">
                <button class="btn btn-primary">Valider</button>
              </div>
          </div>
          <% end %>

      </div>
  </div>
  <!-- END ROW -->

</div>

app/views/completed_project_categories/show.html.erb
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
  <li><a href="<%= completed_project_category_path %>">Nouvelle catégorie de projets</a></li>
    <li><a href="<%= completed_project_categories_path %>">Liste des catégories de projets</a></li>
</ul>
<!-- END BREADCRUMB -->


<div class="page-content-wrap">

  <!-- BEGIN ROW -->
  <div class="row">
    <div class="col-md-12">

      <!-- START DEFAULT DATATABLE -->
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Liste des <strong>catégories de projets</strong></h3>
          <ul class="panel-controls">
            <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
          </ul>
        </div>
        <div class="panel-body">
          <%= notification_messages! %>
          <table class="table datatable">
            <thead>
              <tr>
                <th><%= CompletedProjectCategory.human_attribute_name("name") %></th>
                <th><%= CompletedProjectCategory.human_attribute_name("published") %></th>
                <th>Date de création</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @completed_project_categories.each do |completed_project_category| %>
                <tr>
                  <td>
                    <%= completed_project_category.name %>
                  </td>
                  <td>
                    <% if completed_project_category.published == false %>
                      <div class="list-group-status status-offline"></div>
                    <% else %>
                      <div class="list-group-status status-online"></div>
                    <% end %>
                  </td>
                  <td>
                    <%= completed_project_category.created_at.strftime("%d-%m-%Y") + " à " + completed_project_category.created_at.strftime("%Hh %Mmn") %>
                  </td>
                  <td>
                    <a href = "<%= edit_completed_project_category_path(completed_project_category.id) %>" style = "text-decoration: none;">
                      <span class="fa fa-pencil" style = "margin-right: 15px;" data-toggle="tooltip" data-placement="top" title="" data-original-title="Editer le sujet"></span>
                    </a>
                    <% if completed_project_category.published == false %>
                      <a href = "<%= enable_completed_project_category_path(completed_project_category.id) %>">
                        <span class="fa fa-check" data-toggle="tooltip" data-placement="top" title="" data-original-title="Activer la catégorie"></span>
                      </a>
                    <% else %>
                      <a href = "<%= disable_completed_project_category_path(completed_project_category.id) %>"  style = "text-decoration: none;">
                        <span class="fa fa-times-circle" data-toggle="tooltip" data-placement="top" title="" data-original-title="Désactiver la catégorie"></span>
                      </a>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <!-- END DEFAULT DATATABLE -->
    </div>
  </div>
</div>