config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'competences' => 'home#skills', as: :skills
  get 'a-propos' => 'home#about_us', as: :about_us
  get 'nos-projets' => 'home#portfolio', as: :portfolio

  get 'administrator/subject' => 'subjects#new', as: :subject
  post 'administrator/subject/create' => 'subjects#create', as: :create_subject
  get 'administrator/subject/create' => 'subjects#new'
  get 'administrator/subjects' => 'subjects#show', as: :subjects
  get 'administrator/subject/edit/:subject_id' => 'subjects#edit', as: :edit_subject
  post 'administrator/subject/update/:subject_id' => 'subjects#update', as: :update_subject
  get 'administrator/subject/update/:subject_id' => 'subjects#edit'
  get 'administrator/subject/enable/:subject_id' => 'subjects#enable', as: :enable_subject
  get 'administrator/subject/disable/:subject_id' => 'subjects#disable', as: :disable_subject

  get 'administrator/budget' => 'budgets#new', as: :budget
  post 'administrator/budget/create' => 'budgets#create', as: :create_budget
  get 'administrator/budget/create' => 'budgets#new'
  get 'administrator/budgets' => 'budgets#show', as: :budgets
  get 'administrator/budget/edit/:budget_id' => 'budgets#edit', as: :edit_budget
  post 'administrator/budget/update/:budget_id' => 'budgets#update', as: :update_budget
  get 'administrator/budget/update/:budget_id' => 'budgets#edit'
  get 'administrator/budget/enable/:budget_id' => 'budgets#enable', as: :enable_budget
  get 'administrator/budget/disable/:budget_id' => 'budgets#disable', as: :disable_budget

  get 'administrator/project' => 'projects#new', as: :project
  post 'administrator/project/create' => 'projects#create', as: :create_project
  get 'administrator/project/create' => 'projects#new'
  get 'administrator/projects' => 'projects#show', as: :projects

  get 'administrator/completed_project' => 'completed_projects#new', as: :completed_project
  post 'administrator/completed_project/create' => 'completed_projects#create', as: :create_completed_project
  get 'administrator/completed_project/create' => 'completed_projects#new'
  get 'administrator/completed_projects' => 'completed_projects#show', as: :completed_projects
  get "portfolio/:completed_project_id/details" => "completed_projects#details", as: :completed_project_details

  get 'administrator/completed_project_category' => 'completed_project_categories#new', as: :completed_project_category
  post 'administrator/completed_project_category/create' => 'completed_project_categories#create', as: :create_completed_project_category
  get 'administrator/completed_project_category/create' => 'completed_project_categories#new'
  get 'administrator/completed_project_categories' => 'completed_project_categories#show', as: :completed_project_categories
  get 'administrator/completed_project_category/edit/:completed_project_category_id' => 'completed_project_categories#edit', as: :edit_completed_project_category
  post 'administrator/completed_project_category/update/:completed_project_category_id' => 'completed_project_categories#update', as: :update_completed_project_category
  get 'administrator/completed_project_category/update/:completed_project_category_id' => 'completed_project_categories#edit'
  get 'administrator/completed_project_category/enable/:completed_project_category_id' => 'completed_project_categories#enable', as: :enable_completed_project_category
  get 'administrator/completed_project_category/disable/:completed_project_category_id' => 'completed_project_categories#disable', as: :disable_completed_project_category

  get 'contact' => 'contacts#new', as: :contact
  post 'contact/create' => 'contacts#create', as: :create_contact
  get 'contact/create' => 'contacts#new'
  get 'administrator/contacts' => 'contacts#show', as: :contacts

  get '*rogue_url', :to => 'errors#routing'
  post '*rogue_url', :to => 'errors#routing'
end

app/views/layouts/administrator.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- META SECTION -->
        <title><%= @page_title %></title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="favicon.ico" type="image/x-icon" />
        <!-- END META SECTION -->

        <!-- CSS INCLUDE -->
        <%= stylesheet_link_tag 'back', media: 'all', 'data-turbolinks-track' => true %>
        <!-- EOF CSS INCLUDE -->
    </head>
    <body>
        <!-- START PAGE CONTAINER -->
        <div class="page-container">

            <!-- START PAGE SIDEBAR -->
            <div class="page-sidebar">
                <!-- START X-NAVIGATION -->
                <ul class="x-navigation">

                  <li class="xn-title">Navigation</li>
                  <li class="xn-openable">
                      <a href="#"><span class="fa fa-desktop"></span> <span class="xn-text">Sujets</span></a>
                      <ul>
                          <li><a href="<%= subject_path %>"><span class="fa fa-desktop"></span> Créer un sujet</a></li>
                          <li><a href="<%= subjects_path %>"><span class="fa fa-desktop"></span> Liste des sujets</a></li>
                      </ul>
                  </li>
                  <li>
                      <a href="<%= contacts_path %>"><span class="fa fa-desktop"></span> <span class="xn-text">Contacts</span></a>
                  </li>
                  <li>
                      <a href="<%= projects_path %>"><span class="fa fa-desktop"></span> <span class="xn-text">Projets soumis</span></a>
                  </li>
                  <li class="xn-openable">
                    <a href="#"><span class="fa fa-desktop"></span> <span class="xn-text">Gestion de projets</span></a>
                    <ul>
                      <li class="xn-openable">
                        <a href="#">Budget</a>
                        <ul>
                          <li>
                            <a href="<%= budget_path %>"><span class="fa fa-desktop"></span> Créer un budget</a>
                          </li>
                          <li><a href="<%= budgets_path %>"><span class="fa fa-desktop"></span> Liste des budgets</a></li>
                        </ul>
                      </li>
                    </ul>
                  </li>
                  <li class="active">

                  </li>
                  <li class="xn-openable">
                      <a href="<%= completed_project_path %>"><span class="fa fa-desktop"></span> <span class="xn-text">Projets terminés</span></a>
                      <ul>
                        <li  class="xn-openable">
                          <a href="#">Catégories de projets</a>
                          <ul>
                            <li>
                              <a href="<%= completed_project_category_path %>"><span class="fa fa-desktop"></span> Créer une catégorie</a>
                            </li>
                            <li><a href="<%= completed_project_categories_path %>"><span class="fa fa-desktop"></span> Liste des Catégories</a></li>
                          </ul>
                        </li>
                        <li  class="xn-openable">
                          <a href="#">Gestion des projets</a>
                          <ul>
                            <li>
                              <a href="<%= completed_project_path %>"><span class="fa fa-desktop"></span> Créer un projet</a>
                            </li>
                          </ul>
                        </li>
                      </ul>
                  </li>
                </ul>
                <!-- END X-NAVIGATION -->
            </div>
            <!-- END PAGE SIDEBAR -->

            <!-- PAGE CONTENT -->
            <div class="page-content">

                <!-- START X-NAVIGATION VERTICAL -->
                <ul class="x-navigation x-navigation-horizontal x-navigation-panel">


                    <!-- END TASKS -->
                </ul>
                <!-- END X-NAVIGATION VERTICAL -->


                  <%= yield %>


            </div>
            <!-- END PAGE CONTENT -->
        </div>
        <!-- END PAGE CONTAINER -->

        <!-- MESSAGE BOX-->
        <div class="message-box animated fadeIn" data-sound="alert" id="mb-signout">
            <div class="mb-container">
                <div class="mb-middle">
                    <div class="mb-title"><span class="fa fa-sign-out"></span> Log <strong>Out</strong> ?</div>
                    <div class="mb-content">
                        <p>Are you sure you want to log out?</p>
                        <p>Press No if youwant to continue work. Press Yes to logout current user.</p>
                    </div>
                    <div class="mb-footer">
                        <div class="pull-right">
                            <a href="pages-login.html" class="btn btn-success btn-lg">Yes</a>
                            <button class="btn btn-default btn-lg mb-control-close">No</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END MESSAGE BOX-->

    <!-- START SCRIPTS -->
        <!-- START PLUGINS -->
        <%= javascript_include_tag 'back', media: 'all', 'data-turbolinks-track' => true %>
        <!-- END TEMPLATE -->
    <!-- END SCRIPTS -->
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Start</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>